# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/252/bin/cmake

# The command to remove a file.
RM = /snap/cmake/252/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nick/programming/cs372-battleship

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nick/programming/cs372-battleship

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/252/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/252/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nick/programming/cs372-battleship/CMakeFiles /home/nick/programming/cs372-battleship/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nick/programming/cs372-battleship/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named battleship

# Build rule for target.
battleship: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 battleship
.PHONY : battleship

# fast build rule for target.
battleship/fast:
	$(MAKE) -f CMakeFiles/battleship.dir/build.make CMakeFiles/battleship.dir/build
.PHONY : battleship/fast

drawing.o: drawing.cpp.o

.PHONY : drawing.o

# target to build an object file
drawing.cpp.o:
	$(MAKE) -f CMakeFiles/battleship.dir/build.make CMakeFiles/battleship.dir/drawing.cpp.o
.PHONY : drawing.cpp.o

drawing.i: drawing.cpp.i

.PHONY : drawing.i

# target to preprocess a source file
drawing.cpp.i:
	$(MAKE) -f CMakeFiles/battleship.dir/build.make CMakeFiles/battleship.dir/drawing.cpp.i
.PHONY : drawing.cpp.i

drawing.s: drawing.cpp.s

.PHONY : drawing.s

# target to generate assembly for a file
drawing.cpp.s:
	$(MAKE) -f CMakeFiles/battleship.dir/build.make CMakeFiles/battleship.dir/drawing.cpp.s
.PHONY : drawing.cpp.s

grid.o: grid.cpp.o

.PHONY : grid.o

# target to build an object file
grid.cpp.o:
	$(MAKE) -f CMakeFiles/battleship.dir/build.make CMakeFiles/battleship.dir/grid.cpp.o
.PHONY : grid.cpp.o

grid.i: grid.cpp.i

.PHONY : grid.i

# target to preprocess a source file
grid.cpp.i:
	$(MAKE) -f CMakeFiles/battleship.dir/build.make CMakeFiles/battleship.dir/grid.cpp.i
.PHONY : grid.cpp.i

grid.s: grid.cpp.s

.PHONY : grid.s

# target to generate assembly for a file
grid.cpp.s:
	$(MAKE) -f CMakeFiles/battleship.dir/build.make CMakeFiles/battleship.dir/grid.cpp.s
.PHONY : grid.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/battleship.dir/build.make CMakeFiles/battleship.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/battleship.dir/build.make CMakeFiles/battleship.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/battleship.dir/build.make CMakeFiles/battleship.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... battleship"
	@echo "... edit_cache"
	@echo "... drawing.o"
	@echo "... drawing.i"
	@echo "... drawing.s"
	@echo "... grid.o"
	@echo "... grid.i"
	@echo "... grid.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

